insert into kts_lines(id, active, name, transport_type, duration, description) values (1, 1, '1', 0, 1000, 'Klisa - Liman')
insert into kts_lines(id, active, name, transport_type, duration, description) values (2, 1, '2', 0, 1000, 'Klisa - Liman')
insert into kts_lines(id, active, name, transport_type, duration, description) values (3, 1, '3', 0, 1000, 'Klisa - Liman')
insert into kts_lines(id, active, name, transport_type, duration, description) values (4, 1, '4', 0, 1000, 'Klisa - Liman')
insert into kts_lines(id, active, name, transport_type, duration, description) values (5, 1, '5', 0, 1000, 'Klisa - Liman')
insert into kts_lines(id, active, name, transport_type, duration, description) values (6, 1, '6', 0, 1000, 'Klisa - Liman')
insert into kts_lines(id, active, name, transport_type, duration, description) values (7, 1, '7', 0, 1000, 'Klisa - Liman')
insert into kts_lines(id, active, name, transport_type, duration, description) values (8, 1, '8', 0, 1000, 'Klisa - Liman')
insert into kts_lines(id, active, name, transport_type, duration, description) values (9, 1, '9', 0, 1000, 'Klisa - Liman')

insert into street_path(line_id, street_path) values (1, "Sentandrejski Put 2")
insert into street_path(line_id, street_path) values (1, "Sentandrejski Put 1")
insert into street_path(line_id, street_path) values (1, "Kisacka 2")
insert into street_path(line_id, street_path) values (1, "Kisacka 4")
insert into street_path(line_id, street_path) values (1, "Kisacka 3")
insert into street_path(line_id, street_path) values (1, "Kisacka 1")
insert into street_path(line_id, street_path) values (1, "Jovana Subotica 1")
insert into street_path(line_id, street_path) values (1, "Jovana Subotica 2")
insert into street_path(line_id, street_path) values (1, "Jovana Subotica 3")
insert into street_path(line_id, street_path) values (1, "Bulevar Mihajla Pupina 1")
insert into street_path(line_id, street_path) values (1, "Zarka Zrenjanina 1")
insert into street_path(line_id, street_path) values (1, "Strazilovska 2")
insert into street_path(line_id, street_path) values (1, "Fruskogorska 1")
insert into street_path(line_id, street_path) values (1, "Bulevar Cara Lazara 5")
insert into street_path(line_id, street_path) values (1, "Bulevar Cara Lazara 6")
insert into street_path(line_id, street_path) values (1, "Strazilovska 1")
insert into street_path(line_id, street_path) values (1, "Fruskogorska 3")
insert into street_path(line_id, street_path) values (1, "Fruskogorska 2")



insert into street_path(line_id, street_path) values (2, "Bulevar Jovana Ducica 3")
insert into street_path(line_id, street_path) values (2, "Bulevar Jovana Ducica 2")
insert into street_path(line_id, street_path) values (2, "Bulevar Jovana Ducica 1")
insert into street_path(line_id, street_path) values (2, "Bulevar Slobodana Jovanovica 1")
insert into street_path(line_id, street_path) values (2, "Futoski Put 1")
insert into street_path(line_id, street_path) values (2, "Futoska 4")
insert into street_path(line_id, street_path) values (2, "Futoska 3")
insert into street_path(line_id, street_path) values (2, "Futoska 2")
insert into street_path(line_id, street_path) values (2, "Futoska 1")
insert into street_path(line_id, street_path) values (2, "Jevrejska 1")
insert into street_path(line_id, street_path) values (2, "Jovana Subotica 3")


insert into street_path(line_id, street_path) values (3, "Oblacica Rada 1")
insert into street_path(line_id, street_path) values (3, "Milenka Grcica 1")
insert into street_path(line_id, street_path) values (3, "Milenka Grcica 2")
insert into street_path(line_id, street_path) values (3, "Kornelija Stankovica 1")
insert into street_path(line_id, street_path) values (3, "Rumenacka 1")
insert into street_path(line_id, street_path) values (3, "Rumenacka 2")
insert into street_path(line_id, street_path) values (3, "Bulevar Kralja Petra 1")
insert into street_path(line_id, street_path) values (3, "Bulevar Kralja Petra 2")
insert into street_path(line_id, street_path) values (3, "Brace Jovandic 1")
insert into street_path(line_id, street_path) values (3, "Jovana Subotica 2")
insert into street_path(line_id, street_path) values (3, "Jovana Subotica 3")
insert into street_path(line_id, street_path) values (3, "Bulevar Mihajla Pupina 1")
insert into street_path(line_id, street_path) values (3, "Bulevar Mihajla Pupina 2")
insert into street_path(line_id, street_path) values (3, "Most Duga")
insert into street_path(line_id, street_path) values (3, "Preradoviceva 1")
insert into street_path(line_id, street_path) values (3, "Preradoviceva 2")
insert into street_path(line_id, street_path) values (3, "Preradoviceva 3")


insert into street_path(line_id, street_path) values (4, "Narodnog Fronta 1")
insert into street_path(line_id, street_path) values (4, "Narodnog Fronta 2")
insert into street_path(line_id, street_path) values (4, "Strazilovska 1")
insert into street_path(line_id, street_path) values (4, "Bulevar Cara Lazara 6")
insert into street_path(line_id, street_path) values (4, "Bulevar Cara Lazara 5")
insert into street_path(line_id, street_path) values (4, "Fruskogorska 1")
insert into street_path(line_id, street_path) values (4, "Strazilovska 2")
insert into street_path(line_id, street_path) values (4, "Zarka Zrenjanina 1")
insert into street_path(line_id, street_path) values (4, "Bulevar Mihajla Pupina 1")
insert into street_path(line_id, street_path) values (4, "Jevrejska 1")
insert into street_path(line_id, street_path) values (4, "Bulevar Oslobodjenja 3")
insert into street_path(line_id, street_path) values (4, "Bulevar Oslobodjenja 2")
insert into street_path(line_id, street_path) values (4, "Bulevar Oslobodjenja 1")


insert into street_path(line_id, street_path) values (5, "Avijaticarska 1")
insert into street_path(line_id, street_path) values (5, "Rumenacki Put 1")
insert into street_path(line_id, street_path) values (5, "Rumenacka 1")
insert into street_path(line_id, street_path) values (5, "Rumenacka 2")
insert into street_path(line_id, street_path) values (5, "Hajduk Veljkova 2")
insert into street_path(line_id, street_path) values (5, "Novosadskog Sajma 1")
insert into street_path(line_id, street_path) values (5, "Bulevar Oslobodjenja 3")
insert into street_path(line_id, street_path) values (5, "Jevrejska 1")
insert into street_path(line_id, street_path) values (5, "Jovana Subotica 3")
insert into street_path(line_id, street_path) values (5, "Jovana Subotica 2")
insert into street_path(line_id, street_path) values (5, "Jovana Subotica 1")
insert into street_path(line_id, street_path) values (5, "Temerinska 1")
insert into street_path(line_id, street_path) values (5, "Temerinski Put 1")


insert into street_path(line_id, street_path) values (6, "Banjalucka 1")
insert into street_path(line_id, street_path) values (6, "Branka Copica 2")
insert into street_path(line_id, street_path) values (6, "Branka Copica 1")
insert into street_path(line_id, street_path) values (6, "Cirila i Metodija 2")
insert into street_path(line_id, street_path) values (6, "Cirila i Metodija 1")
insert into street_path(line_id, street_path) values (6, "Fejes Klare 1")
insert into street_path(line_id, street_path) values (6, "Vrsacka 1")
insert into street_path(line_id, street_path) values (6, "Futoski Put 1")
insert into street_path(line_id, street_path) values (6, "Futoska 4")
insert into street_path(line_id, street_path) values (6, "Futoska 3")
insert into street_path(line_id, street_path) values (6, "Futoska 2")
insert into street_path(line_id, street_path) values (6, "Futoska 1")
insert into street_path(line_id, street_path) values (6, "Jevrejska 1")
insert into street_path(line_id, street_path) values (6, "Bulevar Mihajla Pupina 1")
insert into street_path(line_id, street_path) values (6, "Bulevar Mihajla Pupina 2")
insert into street_path(line_id, street_path) values (6, "Beogradski Kej 1")
insert into street_path(line_id, street_path) values (6, "Marka Miljanova 2")
insert into street_path(line_id, street_path) values (6, "Marka Miljanova 1")
insert into street_path(line_id, street_path) values (6, "Djordja Rajkovica 1")


insert into street_path(line_id, street_path) values (7, "Bulevar Jovana Ducica 1")
insert into street_path(line_id, street_path) values (7, "Bulevar Jovana Ducica 2")
insert into street_path(line_id, street_path) values (7, "Bulevar Jovana Ducica 3")
insert into street_path(line_id, street_path) values (7, "Bulevar Slobodana Jovanovica 2")
insert into street_path(line_id, street_path) values (7, "Bulevar Vojvode Stepe 1")
insert into street_path(line_id, street_path) values (7, "Kornelija Stankovica 3")
insert into street_path(line_id, street_path) values (7, "Kornelija Stankovica 2")
insert into street_path(line_id, street_path) values (7, "Kornelija Stankovica 1")
insert into street_path(line_id, street_path) values (7, "Rumenacka 1")
insert into street_path(line_id, street_path) values (7, "Bulevar Jase Tomica 2")
insert into street_path(line_id, street_path) values (7, "Bulevar Oslobodjenja 1")
insert into street_path(line_id, street_path) values (7, "Bulevar Oslobodjenja 2")
insert into street_path(line_id, street_path) values (7, "Bulevar Oslobodjenja 3")
insert into street_path(line_id, street_path) values (7, "Bulevar Oslobodjenja 4")
insert into street_path(line_id, street_path) values (7, "Bulevar Oslobodjenja 5")
insert into street_path(line_id, street_path) values (7, "Bulevar Oslobodjenja 6")
insert into street_path(line_id, street_path) values (7, "Narodnog Fronta 1")
insert into street_path(line_id, street_path) values (7, "Ive Andrica 1")
insert into street_path(line_id, street_path) values (7, "Ive Andrica 2")
insert into street_path(line_id, street_path) values (7, "Bulevar Cara Lazara 4")
insert into street_path(line_id, street_path) values (7, "Bulevar Patrijarha Pavla 1")
insert into street_path(line_id, street_path) values (7, "Bulevar Patrijarha Pavla 2")
insert into street_path(line_id, street_path) values (7, "Bulevar Kneza Milosa 1")


insert into street_path(line_id, street_path) values (8, "Bulevar Jovana Ducica 3")
insert into street_path(line_id, street_path) values (8, "Bulevar Vojvode Stepe 3")
insert into street_path(line_id, street_path) values (8, "Bate Brkica 1")
insert into street_path(line_id, street_path) values (8, "Bulevar Jovana Ducica 1")
insert into street_path(line_id, street_path) values (8, "Radomira Rase Radujkova 1")
insert into street_path(line_id, street_path) values (8, "Hadzi Ruvimova 1")
insert into street_path(line_id, street_path) values (8, "Bulevar Kralja Petra 1")
insert into street_path(line_id, street_path) values (8, "Bulevar Kralja Petra 2")
insert into street_path(line_id, street_path) values (8, "Bulevar Kralja Petra 3")
insert into street_path(line_id, street_path) values (8, "Kisacka 1")
insert into street_path(line_id, street_path) values (8, "Jovana Subotica 1")
insert into street_path(line_id, street_path) values (8, "Jovana Subotica 2")
insert into street_path(line_id, street_path) values (8, "Jovana Subotica 3")
insert into street_path(line_id, street_path) values (8, "Bulevar Mihajla Pupina 1")
insert into street_path(line_id, street_path) values (8, "Zarka Zrenjanina 1")
insert into street_path(line_id, street_path) values (8, "Strazilovska 2")
insert into street_path(line_id, street_path) values (8, "Fruskogorska 1")
insert into street_path(line_id, street_path) values (8, "Bulevar Cara Lazara 6")
insert into street_path(line_id, street_path) values (8, "Bulevar Cara Lazara 5")
insert into street_path(line_id, street_path) values (8, "Strazilovska 1")
insert into street_path(line_id, street_path) values (8, "Fruskogorska 3")
insert into street_path(line_id, street_path) values (8, "Fruskogorska 2")


insert into street_path(line_id, street_path) values (9, "Bulevar Jovana Ducica 3")
insert into street_path(line_id, street_path) values (9, "Bulevar Jovana Ducica 2")
insert into street_path(line_id, street_path) values (9, "Bulevar Jovana Ducica 1")
insert into street_path(line_id, street_path) values (9, "Bulevar Slobodana Jovanovica 1")
insert into street_path(line_id, street_path) values (9, "Futoski Put 1")
insert into street_path(line_id, street_path) values (9, "Futoska 4")
insert into street_path(line_id, street_path) values (9, "Cara Dusana 3")
insert into street_path(line_id, street_path) values (9, "Cara Dusana 2")
insert into street_path(line_id, street_path) values (9, "Bulevar Cara Lazara 3")
insert into street_path(line_id, street_path) values (9, "Bulevar Cara Lazara 1")
insert into street_path(line_id, street_path) values (9, "Bulevar Cara Lazara 6")
insert into street_path(line_id, street_path) values (9, "Bulevar Cara Lazara 5")
insert into street_path(line_id, street_path) values (9, "Fruskogorska 1")
insert into street_path(line_id, street_path) values (9, "Strazilovska 2")
insert into street_path(line_id, street_path) values (9, "Zarka Zrenjanina 1")
insert into street_path(line_id, street_path) values (9, "Bulevar Mihajla Pupina 2")
insert into street_path(line_id, street_path) values (9, "Most Duga")
insert into street_path(line_id, street_path) values (9, "Preradoviceva 1")
insert into street_path(line_id, street_path) values (9, "Preradoviceva 2")
insert into street_path(line_id, street_path) values (9, "Preradoviceva 3")

insert into stations(id, active, address, name, x, y) values (1, 1, 'Bulevar Oslobodjenja 14', 'Bul. Oslobodjenja - Lutrija', 0, 0)
insert into stations(id, active, address, name, x, y) values (2, 1, 'Bulevar Oslobodjenja 50', 'Aleksandar zgrada', 0, 0)

insert into line_and_station(line_id, station_id, station_order) values (1, 1, 1)
insert into line_and_station(line_id, station_id, station_order) values (1, 2, 2)

insert into zones(id, active, name, sub_zone_id) values (1, true, 'gradska', NULL)
insert into zones(id, active, name, sub_zone_id) values (2, true, 'prigradska', 1)



INSERT INTO users(id, document, document_verified, first_name, last_name, username, password, role, user_type_demo) VALUES (1, 'document-test.jpg', 1, 'Jovan', 'Lakovic', 'user1', '12345678', 1, 1)
INSERT INTO users(id, first_name, last_name, username, password, role) VALUES (2, 'Marko', 'Markovic', 'admin', 'admin', 0) 
insert into users(id, document, document_verified, first_name, last_name, password, role, user_type_demo, username) values (3, null, 0, 'Sara', 'Petrovic', '123', 1, 1, 'Sara')
INSERT INTO users(id, document, document_verified, first_name, last_name, username, password, role, user_type_demo) VALUES (4, 'document-test.jpg', 1, 'Nemanja', 'Nemanjic', 'user2', '1234', 1, 0)
insert into users(id, first_name, last_name, username, password, role, user_type_demo) values (6, 'Sara', 'Petrovic', 'sara123', '12345678', 1, 1)
INSERT INTO users(id, first_name, last_name, username, password, role) VALUES (9, 'Marko', 'Balenovic', 'administrator', 'administrator', 0) 
insert into users(id, first_name, last_name, username, password, role, user_type_demo) values (7, 'Marko', 'Markovic', 'admin123', 'adminadmin', 0, 0)
insert into users(id, first_name, last_name, username, password, role, user_type_demo, document, document_verified) values (8, 'Milan', 'Markovic', 'client', 'client', 1, 0, 'dssd', 1)
INSERT INTO users(id, first_name, last_name, username, password, ROLE, document, document_verified, user_type_demo) VALUES (12, 'Ime', 'Prezime', 'userNoDocument', '12345678', 1, NULL, 0, 0)

insert into users(id, first_name, last_name, username, password, role, user_type_demo) values (10, 'Marko', 'Markovic', 'conductor', 'conductor', 2, 0)

insert into zones_stations(zone_id, stations_id) values (1,1)
insert into zones_stations(zone_id, stations_id) values (1,2)

insert into vehicles(id, active, vehicle_name, vehicle_type, free, free_from) values (1, true, 'vozilo broj 1', 0, true, '2019-01-01 00:00:00')

insert into kts_route(id, date, line_id, vehicle_id) values(1, '2019-02-02 00:00:00', 1, 1)

insert into route_schedule(id, active, active_from, line_id) values (1, true, '2019-02-01 00:00:00', 1)
insert into weekday_schedule(route_schedule_id, weekday) values (1, '07:00:00')
insert into weekday_schedule(route_schedule_id, weekday) values (1, '13:00:00')
insert into weekday_schedule(route_schedule_id, weekday) values (1, '20:00:00')
insert into saturday_schedule(route_schedule_id, saturday) values (1, '11:40:00')
insert into saturday_schedule(route_schedule_id, saturday) values (1, '16:40:00')
insert into sunday_schedule(route_schedule_id, sunday) values (1, '10:00:00')

insert into ticket(id, active, start_time, end_time, price, ticket_type, ticket_temporal, transport_type, user_id, line_id, route_id, zone_id) values (1, 1, null, null, 100, 'route_ticket', 3, 0, 3, null, 1, null)
insert into ticket(id, active, start_time, end_time, price, ticket_type, ticket_temporal, transport_type, user_id, line_id, route_id, zone_id) values (2, 1, null, null, 60, 'zone_ticket', 0, 0, 3, null, null, 2)
